### ISSUE TITLE
Adaptive card not displayed in the BotFramework-DirectLine-DotNet

### ISSUE THREAD

**Issue by dstvishnu** [microsoft/BotFramework-DirectLine-DotNet#10]
When we are trying to send a simple adaptive card it is getting displayed in the webchat and emulator but while using it in a client application(Mobile which uses directline .net client it is not getting displayed. Is there anything we have to specially do to handle it? The adaptive card is getting displayed in the emulator as well as in the webchat)

**Comment by EricDahlvang** [comment]
Hi @dstvishnu 

The dotnet directline client does not have a corresponding renderer within the package.  If you are rendering only adaptive cards, one of these libraries might be helpful: 
https://github.com/microsoft/AdaptiveCards/tree/main/source

Another option is to host WebChat your client.
