### ISSUE TITLE
Mention Entities are ignored when sending Activity

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-DirectLine-DotNet#8]
## Version
What package version of the SDK are you using. __Microsoft.Bot.Connector.DirectLine 3.0.2__

## Describe the bug

I'm trying to send an `Activity` with mentions to my Bot, but the mentions always show as empty on the receiving end. Here's a rough outline of the code I'm using:

```csharp
// Code to set up DirectLine client and start a conversation.

var activity = new Activity
{
    Type = "message",
    From = new ChannelAccount { Id="123", Name="haacked" },
    Text = "hello @haacked",
    Entities = new List<Entity> {
      new Entity
            {
                Type = "mention",
                Properties =
                    JObject.Parse(@"{{""mentioned"": {{""id"": ""123:T123"", ""name"": ""haacked"" }} }}")
            }
   }
};
await client.Conversations.PostActivityWithHttpMessagesAsync(
                conversation.ConversationId,
                activity);
``` 

I can see that my bot does receive the message, but the `Mentions` property is empty. 😦 

## To Reproduce
1. Deploy a .NET Bot Framework bot to Azure
2. Register the bot using Azure Bot Service.
3. Configure a DirectLine connection to the bot.
4. Write a console app using the DirectLine C# client library that sends an `Activity` containing `Entities` to `https://directline.botframework.com/`.

## Expected behavior
The bot would receive an `Activity` with a populated `Mentions` property.

## Actual behavior
The bot receives the `Activity` but the `Mentions` property is empty.

[bug]

**Comment by haacked** [comment]
Sorry for the noise. I didn't change my code, but I just tested this and it's working now. I'll do more testing to make sure it continues to work, but I'll close the issue for now.

**Comment by EricDahlvang** [comment]
Thanks for the follow up @haacked
